### ISSUE TITLE
[Ch07] 컨피그맵과 시크릿: 애플리케이션 설정

### ISSUE THREAD

**Issue by lees741** [MediaTech-Junior/kubernetes-in-action#7]
# Ch07. 컨피그맵과 시크릿: 애플리케이션 설정

## 7.1 컨테이너화된 애플리케이션 설정
- 일반적으로 새 애플리케이션에 설정을 전달할 때는 명령줄 인수로 전달하거나 설정 파일에 저장하는 방법을 사용함
- 컨테이너화된 애플리케이션에서 널리 사용하는 방법으로 환경변수를 사용하는 방법이 있음

### 컨테이너 내부에서 설정 파일을 사용하기 힘든 이유
- 이미지 자체에 파일을 포함해 빌드하는 경우 해당 이미지에 접근할 수 있는 모든 사람이 볼 수 있기 때문에 소스 코드에 설정 내용을 넣고 하드코딩하는 것과 다를게 없음
- 설정 파일이 포함된 볼륨을 컨테이너에 마운트하는 방법은 컨테이너를 시작하기 전 파일이 볼륨에 기록되어 있는지 확인하는 과정이 필요해 번거로움

### 7.2.1 도커에서 명령어와 인자 정의
- Docker에서 `ENTRYPOINT`와 명령을 통해 컨테이너가 시작될 때 호출될 명령어를 정의하고 `CMD` 명령을 통해 `ENTRYPOINT`에 전달되는 인자를 정의할 수 있음

### 7.2.2 쿠버네티스에서 명령과 인자 재정의
- 쿠버네티스에서 컨테이너를 정의할 때 `ENTRYPOINT`와 `CMD` 둘 다 재정의 할 수 있음
- `spec.containers.command`를 통해 `ENTRYPOINT`를 재정의, `spec.containers.args`를 통해 `CMD`를 재정의 할 수 있음
- 보통 사용자 정의 인자만 지정하고 명령을 재정의하는 경우는 거의 없음
```yaml
kind: Pod
spec:
  containers:
  - image: some/image
    command: ["/bin/command"]
    args: ["arg1", "arg2", "arg3"]
```
> 💡 인자가 많은 경우 위 목록에서 사용한 배열 표기법 대신 다음 표기법을 사용할 수 있음
```yaml
args:
  - foo
  - bar
  - "15"
```
> 💡 문자열 값은 따옴표로 묶을 필요가 없지만 숫자는 묶어야 함

## 7.3 컨테이너의 환경변수 설정
- 파드의 각 컨테이너를 위한 환경변수 리스트를 지정할 수 있음
- 파드 수준에서 환경변수를 설정하고 컨테이너에서 상속받는 옵션은 없음

### 7.3.1 컨테이너 정의에 환경변수 지정
```yaml
kind: Pod
spec:
  containers:
  - image: luksa/fortune:env
    env:
    - name: INTERVAL
      value: "30"
```
- 각 컨테이너에 환경변수를 설정할 때 동일한 네임스페이스 내의 각 서비스에 환경변수를 자동으로 노출
  - 같은 네임스페이스에 존재하는 동일한 이름의 환경변수를 덮어쓸 가능성???

### 7.3.2 변숫값에서 다른 환경변수 참조
- $(VAR) 구문을 사용해 이미 정의된 환경변수나 기타 기존 변수 참조 가능
```yaml
env:
  - name: FIRST_VAR
    value: "foo"
  - name: SECOND_VAR
    value: "$(FIRST_VAR)bar"
```

### 7.3.3 하드코딩된 환경변수의 단점
- 환경변수는 운영환경과 개발환경 분리가 필요함
- 파드 정의가 운영환경과 개발환경에서 동일한 경우 파드 정의에서 설정만 분리하는 것이 필요함 (파드 정의 재사용을 위해)

### 7.4.1 컨피그맵 소개
- 쿠버네티스에서는 설정 옵션을 별도 오브젝트로 분리할 수 있음
- 컨피그맵은 키/값 쌍으로 구성된 맵
- 파드는 컨피그맵을 환경변수나 컨피그맵 볼륨을 통해 사용할 수 있음

### 7.4.2 컨피그맵 생성
- 개별 파일, 디렉터리, 문자열 값으로 컨피그맵을 생성할 수 있음

### 7.4.3 컨피그맵 항목을 환경변수로 컨테이너에 전달
- 파드 정의에서 환경변수 정의할 때 `value`를 `valueFrom`으로 변경
```yaml
env:
  - name: INTERVAL
    valueFrom:
       configMapKeyRef:
         name: fortune-config
         key: sleep-interval
```
- 만약 파드를 생성할 때 지정한 컨피그맵이 존재하지 않는다면 컨테이너는 실행되지 않음
  - `configMapKeyRef.optional: true`로 지정해 컨피그맵 참조를 옵션으로 지정할 수 있음 (컨피그맵이 존재하지 않아도 컨테이너 실행됨)

### 7.4.4 컨피그맵의 모든 항목을 한 번에 환경변수로 전달
- 쿠버네티스 버전 1.6부터는 컨피그맵의 모든 항목을 환경변수로 노출하는 방법 제공
- `env`속성 대신 `envFrom`으로 변경
```yaml
spec:
  containers:
  - image: some-image
    envFrom:
    - prefix: CONFIG_
      configMapRef:
        name: my-config-map
```
- prefix를 지정하면 prefix+configMap 키가 환경변수 이름으로 설정됨 (ex. CONFIG_FOO)
- 키가 대시(-)를 포함하는 등 유효한 환경변수 이름이 아닌 경우 항목을 건너뜀

### 7.4.5 컨피그맵 항목을 명령줄 인자로 전달
- 앞서 말한 `arg`필드에서 직접 컨피그맵 항목을 참조할 수는 없음
- 우선 컨피그맵 항목을 환경변수로 초기화하고 이를 인자로 참조하도록 지정 가능
  - $(ENVVARNAME) 문법 사용

### 7.4.6 컨피그맵 볼륨을 사용해 컨피그맵 항목을 파일로 노출
- 특수 볼륨 유형 중 하나인 컨피그맵 볼륨을 통해 파일로 컨피그맵의 각 항목을 노출 가능
- `items`속성을 통해 볼륨에 포함할 항목을 특정할 수 있음 (ex. 환경변수로 전달할 키/값은 제외 가능)

#### 디렉터리 안에 다른 파일을 숨기지 않고 개별 컨피그맵 항목을 파일로 마운트
- 일반적으로 리눅스에서 파일시스템을 비어 있지 않은 디렉터리에 마운트하면 파일시스템이 마운트돼 있는 동안 기존 파일에 접근할 수 없음
- 기존 디렉터리 안에 있는 파일을 숨기지 않고 컨피그맵 항목을 개별 파일로 추가하려면 `subPath`속성 이용
```yaml
spec:
  containers:
  - image: some-image
    volumeMounts:
    - name: myvolume
      mountPath: /etc/somconfig.conf
      subPath: myconfing.conf
```

#### 컨피그맵 볼륨 안에 있는 파일 권한 설정
- 기본적으로 컨피그맵 볼륨의 모든 파일 권한은 644(rw-r--r--)로 설정됨
- 볼륨 정의 안에 있는 `defaultMode` 속성을 설정해 변경 가능

### 7.4.7 애플리케이션을 재시작하지 않고 애플리케이션 설정 업데이트
- 환경변수, 명령줄 인수를 설정 소스로 사용하면 프로세스가 실행되는 동안 업데이트 할 수 없음
- 컨피그맵 볼륨을 사용하면 파드를 재생성하거나 컨테이너 재시작 필요 없이 설정 업데이트 가능 (애플리케이션에서 다시 읽는 것은 직접 구현해야 함)
- 컨피그맵이 업데이트되면 새 디렉터리를 생성하고 모든 파일을 쓴 다음 컨피그맵 볼륨이 가리키는 심볼릭 링크를 업데이트함 > 모든 파일을 안전하게 한 번에 업데이트
- subPath를 사용하는 컨피그맵은 자동으로 업데이트 되지 않음
